# TCL File Generated by Component Editor 18.1
# Thu Jul 11 12:45:44 CEST 2024
# DO NOT MODIFY


# 
# sc_hub "Slow Control Hub" v2.7.11
# Yifeng Wang 2024.07.11.12:45:44
# Interconnect SWB and FEB. Translate the Mu3e Slow-Control packet into Avalon Memory-Mapped transations. Support read/write in burst mode. Out-of-Order is not allowed. 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sc_hub
# 
set_module_property DESCRIPTION "Slow control hub which couples sc_rx and NIOS II to the datapath entities"
set_module_property NAME sc_hub
set_module_property VERSION 2.7.11
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Control Plane/Modules"
set_module_property AUTHOR "Yifeng Wang"
set_module_property DISPLAY_NAME "Slow Control Hub"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sc_hub_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sc_hub.vhd VHDL PATH sc_hub.vhd
add_fileset_file alt_fifo_w32d256.vhd VHDL PATH ./alt_ip/alt_fifo_w32d256/alt_fifo_w32d256.vhd
add_fileset_file alt_fifo_w40d512.vhd VHDL PATH ./alt_ip/alt_fifo_w40d512/alt_fifo_w40d512.vhd
add_fileset_file sc_hub_top.vhd VHDL PATH sc_hub_top.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter BACKPRESSURE BOOLEAN true
set_parameter_property BACKPRESSURE DEFAULT_VALUE true
set_parameter_property BACKPRESSURE DISPLAY_NAME BACKPRESSURE
set_parameter_property BACKPRESSURE TYPE BOOLEAN
set_parameter_property BACKPRESSURE UNITS None
set_parameter_property BACKPRESSURE HDL_PARAMETER true
add_parameter SCHEDULER_USE_PKT_TRANSFER BOOLEAN true
set_parameter_property SCHEDULER_USE_PKT_TRANSFER DEFAULT_VALUE true
set_parameter_property SCHEDULER_USE_PKT_TRANSFER DISPLAY_NAME SCHEDULER_USE_PKT_TRANSFER
set_parameter_property SCHEDULER_USE_PKT_TRANSFER TYPE BOOLEAN
set_parameter_property SCHEDULER_USE_PKT_TRANSFER UNITS None
set_parameter_property SCHEDULER_USE_PKT_TRANSFER HDL_PARAMETER true
add_parameter INVERT_RD_SIG BOOLEAN true
set_parameter_property INVERT_RD_SIG DEFAULT_VALUE true
set_parameter_property INVERT_RD_SIG DISPLAY_NAME INVERT_RD_SIG
set_parameter_property INVERT_RD_SIG TYPE BOOLEAN
set_parameter_property INVERT_RD_SIG UNITS None
set_parameter_property INVERT_RD_SIG HDL_PARAMETER true
add_parameter DEBUG NATURAL 1 ""
set_parameter_property DEBUG DEFAULT_VALUE 1
set_parameter_property DEBUG DISPLAY_NAME DEBUG
set_parameter_property DEBUG WIDTH ""
set_parameter_property DEBUG TYPE NATURAL
set_parameter_property DEBUG ENABLED false
set_parameter_property DEBUG UNITS None
set_parameter_property DEBUG ALLOWED_RANGES 0:2147483647
set_parameter_property DEBUG DESCRIPTION ""
set_parameter_property DEBUG HDL_PARAMETER true


# 
# display items
# 


# 
# connection point hub_clock
# 
add_interface hub_clock clock end
set_interface_property hub_clock clockRate 0
set_interface_property hub_clock ENABLED true
set_interface_property hub_clock EXPORT_OF ""
set_interface_property hub_clock PORT_NAME_MAP ""
set_interface_property hub_clock CMSIS_SVD_VARIABLES ""
set_interface_property hub_clock SVD_ADDRESS_GROUP ""

add_interface_port hub_clock i_clk clk Input 1


# 
# connection point hub_reset
# 
add_interface hub_reset reset end
set_interface_property hub_reset associatedClock hub_clock
set_interface_property hub_reset synchronousEdges DEASSERT
set_interface_property hub_reset ENABLED true
set_interface_property hub_reset EXPORT_OF ""
set_interface_property hub_reset PORT_NAME_MAP ""
set_interface_property hub_reset CMSIS_SVD_VARIABLES ""
set_interface_property hub_reset SVD_ADDRESS_GROUP ""

add_interface_port hub_reset i_rst reset Input 1


# 
# connection point hub_avmm
# 
add_interface hub_avmm avalon start
set_interface_property hub_avmm addressUnits WORDS
set_interface_property hub_avmm associatedClock hub_clock
set_interface_property hub_avmm associatedReset hub_reset
set_interface_property hub_avmm bitsPerSymbol 8
set_interface_property hub_avmm burstOnBurstBoundariesOnly false
set_interface_property hub_avmm burstcountUnits WORDS
set_interface_property hub_avmm doStreamReads false
set_interface_property hub_avmm doStreamWrites false
set_interface_property hub_avmm holdTime 0
set_interface_property hub_avmm linewrapBursts false
set_interface_property hub_avmm maximumPendingReadTransactions 0
set_interface_property hub_avmm maximumPendingWriteTransactions 0
set_interface_property hub_avmm readLatency 0
set_interface_property hub_avmm readWaitTime 1
set_interface_property hub_avmm setupTime 0
set_interface_property hub_avmm timingUnits Cycles
set_interface_property hub_avmm writeWaitTime 0
set_interface_property hub_avmm ENABLED true
set_interface_property hub_avmm EXPORT_OF ""
set_interface_property hub_avmm PORT_NAME_MAP ""
set_interface_property hub_avmm CMSIS_SVD_VARIABLES ""
set_interface_property hub_avmm SVD_ADDRESS_GROUP ""

add_interface_port hub_avmm avm_m0_address address Output 16
add_interface_port hub_avmm avm_m0_read read Output 1
add_interface_port hub_avmm avm_m0_readdata readdata Input 32
add_interface_port hub_avmm avm_m0_writeresponsevalid writeresponsevalid Input 1
add_interface_port hub_avmm avm_m0_response response Input 2
add_interface_port hub_avmm avm_m0_write write Output 1
add_interface_port hub_avmm avm_m0_writedata writedata Output 32
add_interface_port hub_avmm avm_m0_waitrequest waitrequest Input 1
add_interface_port hub_avmm avm_m0_readdatavalid readdatavalid Input 1
add_interface_port hub_avmm avm_m0_burstcount burstcount Output 9
add_interface_port hub_avmm avm_m0_flush flush Output 1


# 
# connection point hub_sc_packet_downlink
# 
add_interface hub_sc_packet_downlink conduit end
set_interface_property hub_sc_packet_downlink associatedClock hub_clock
set_interface_property hub_sc_packet_downlink associatedReset hub_reset
set_interface_property hub_sc_packet_downlink ENABLED true
set_interface_property hub_sc_packet_downlink EXPORT_OF ""
set_interface_property hub_sc_packet_downlink PORT_NAME_MAP ""
set_interface_property hub_sc_packet_downlink CMSIS_SVD_VARIABLES ""
set_interface_property hub_sc_packet_downlink SVD_ADDRESS_GROUP ""

add_interface_port hub_sc_packet_downlink i_linkin_data data Input 32
add_interface_port hub_sc_packet_downlink i_linkin_datak datak Input 4
add_interface_port hub_sc_packet_downlink o_linkin_ready ready Output 1


# 
# connection point hub_sc_packet_uplink
# 
add_interface hub_sc_packet_uplink avalon_streaming start
set_interface_property hub_sc_packet_uplink associatedClock hub_clock
set_interface_property hub_sc_packet_uplink associatedReset hub_reset
set_interface_property hub_sc_packet_uplink dataBitsPerSymbol 36
set_interface_property hub_sc_packet_uplink errorDescriptor ""
set_interface_property hub_sc_packet_uplink firstSymbolInHighOrderBits true
set_interface_property hub_sc_packet_uplink maxChannel 0
set_interface_property hub_sc_packet_uplink readyLatency 0
set_interface_property hub_sc_packet_uplink ENABLED true
set_interface_property hub_sc_packet_uplink EXPORT_OF ""
set_interface_property hub_sc_packet_uplink PORT_NAME_MAP ""
set_interface_property hub_sc_packet_uplink CMSIS_SVD_VARIABLES ""
set_interface_property hub_sc_packet_uplink SVD_ADDRESS_GROUP ""

add_interface_port hub_sc_packet_uplink aso_to_uplink_data data Output 36
add_interface_port hub_sc_packet_uplink aso_to_uplink_valid valid Output 1
add_interface_port hub_sc_packet_uplink aso_to_uplink_ready ready Input 1
add_interface_port hub_sc_packet_uplink aso_to_uplink_startofpacket startofpacket Output 1
add_interface_port hub_sc_packet_uplink aso_to_uplink_endofpacket endofpacket Output 1

