`timescale 1ns/1ps

`ifdef SC_HUB_BUS_AXI4
bind sc_hub_uvm_tb_top sc_hub_uvm_assertions_bind assertions_bind_inst (
  .clk                  (clk),
  .rst                  (rst),
  .link_ready           (sc_pkt_vif.ready),
  .link_data            (sc_pkt_vif.data),
  .link_datak           (sc_pkt_vif.datak),
  .uplink_valid         (sc_reply_vif.valid),
  .uplink_ready         (sc_reply_vif.ready),
  .uplink_data          (sc_reply_vif.data),
  .uplink_sop           (sc_reply_vif.sop),
  .uplink_eop           (sc_reply_vif.eop),
  .dl_fifo_usedw        ({6'd0, dut_inst.dl_fifo_usedw}),
  .dl_fifo_full         (dut_inst.dl_fifo_full),
  .wr_data_rdreq        (dut_inst.wr_data_rdreq),
  .wr_data_empty        (dut_inst.wr_data_empty),
  .pkt_rx_download_ready(dut_inst.download_ready_int),
  .pkt_rx_payload_space_ready(dut_inst.pkt_rx_inst.payload_space_ready),
  .tx_reply_start       (dut_inst.tx_reply_start),
  .tx_reply_ready       (dut_inst.tx_reply_ready),
  .tx_reply_has_data    (dut_inst.tx_reply_has_data),
  .tx_reply_suppress    (dut_inst.tx_reply_suppress),
  .tx_reply_len         (dut_inst.tx_reply_info.rw_length),
  .bp_usedw             ({6'd0, dut_inst.bp_usedw}),
  .dl_fifo_depth        (16'(DUT_DL_FIFO_DEPTH)),
  .bp_fifo_depth        (16'(DUT_BP_FIFO_DEPTH)),
  .axi_rd_done          (dut_inst.bus_rd_done),
  .axi_rd_done_tag      (dut_inst.bus_rd_done_tag),
  .axi_awid             (bus_vif.awid),
  .axi_awaddr           (bus_vif.awaddr),
  .axi_awlen            (bus_vif.awlen),
  .axi_awsize           (bus_vif.awsize),
  .axi_awburst          (bus_vif.awburst),
  .axi_awvalid          (bus_vif.awvalid),
  .axi_awready          (bus_vif.awready),
  .axi_wdata            (bus_vif.wdata),
  .axi_wstrb            (bus_vif.wstrb),
  .axi_wlast            (bus_vif.wlast),
  .axi_wvalid           (bus_vif.wvalid),
  .axi_wready           (bus_vif.wready),
  .axi_bid              (bus_vif.bid),
  .axi_bresp            (bus_vif.bresp),
  .axi_bvalid           (bus_vif.bvalid),
  .axi_bready           (bus_vif.bready),
  .axi_arid             (bus_vif.arid),
  .axi_araddr           (bus_vif.araddr),
  .axi_arlen            (bus_vif.arlen),
  .axi_arsize           (bus_vif.arsize),
  .axi_arburst          (bus_vif.arburst),
  .axi_arvalid          (bus_vif.arvalid),
  .axi_arready          (bus_vif.arready),
  .axi_rid              (bus_vif.rid),
  .axi_rdata            (bus_vif.rdata),
  .axi_rresp            (bus_vif.rresp),
  .axi_rlast            (bus_vif.rlast),
  .axi_rvalid           (bus_vif.rvalid),
  .axi_rready           (bus_vif.rready)
);
`else
bind sc_hub_uvm_tb_top sc_hub_uvm_assertions_bind assertions_bind_inst (
  .clk                  (clk),
  .rst                  (rst),
  .link_ready           (sc_pkt_vif.ready),
  .link_data            (sc_pkt_vif.data),
  .link_datak           (sc_pkt_vif.datak),
  .uplink_valid         (sc_reply_vif.valid),
  .uplink_ready         (sc_reply_vif.ready),
  .uplink_data          (sc_reply_vif.data),
  .uplink_sop           (sc_reply_vif.sop),
  .uplink_eop           (sc_reply_vif.eop),
  .dl_fifo_usedw        ({6'd0, dut_inst.dl_fifo_usedw}),
  .dl_fifo_full         (dut_inst.dl_fifo_full),
  .wr_data_rdreq        (dut_inst.wr_data_rdreq),
  .wr_data_empty        (dut_inst.wr_data_empty),
  .pkt_rx_download_ready(dut_inst.download_ready_int),
  .pkt_rx_payload_space_ready(dut_inst.pkt_rx_inst.payload_space_ready),
  .tx_reply_start       (dut_inst.tx_reply_start),
  .tx_reply_ready       (dut_inst.tx_reply_ready),
  .tx_reply_has_data    (dut_inst.tx_reply_has_data),
  .tx_reply_suppress    (dut_inst.tx_reply_suppress),
  .tx_reply_len         (dut_inst.tx_reply_info.rw_length),
  .bp_usedw             ({6'd0, dut_inst.bp_usedw}),
  .dl_fifo_depth        (16'(DUT_DL_FIFO_DEPTH)),
  .bp_fifo_depth        (16'(DUT_BP_FIFO_DEPTH)),
  .avm_read             (bus_vif.read),
  .avm_write            (bus_vif.write),
  .avm_address          (bus_vif.address),
  .avm_writedata        (bus_vif.writedata),
  .avm_waitrequest      (bus_vif.waitrequest),
  .avm_response         (bus_vif.response),
  .avm_burstcount       (bus_vif.burstcount)
);
`endif

module tb_top;
  sc_hub_uvm_tb_top harness();
endmodule
