module sc_hub_uvm_assertions_bind (
  input logic clk,
  input logic rst,
  input logic link_ready,
  input logic [31:0] link_data,
  input logic [3:0]  link_datak,
  input logic uplink_valid,
  input logic uplink_ready,
  input logic [35:0] uplink_data,
  input logic uplink_sop,
  input logic uplink_eop,
  input logic [15:0] dl_fifo_usedw,
  input logic        dl_fifo_full,
  input logic        wr_data_rdreq,
  input logic        wr_data_empty,
  input logic        pkt_rx_download_ready,
  input logic        pkt_rx_payload_space_ready,
  input logic        tx_reply_start,
  input logic        tx_reply_ready,
  input logic        tx_reply_has_data,
  input logic        tx_reply_suppress,
  input logic [15:0] tx_reply_len,
  input logic [15:0] bp_usedw,
  input logic [15:0] dl_fifo_depth,
  input logic [15:0] bp_fifo_depth
`ifdef SC_HUB_BUS_AXI4
  ,
  input logic        axi_rd_done,
  input logic [3:0]  axi_rd_done_tag,
  input logic [3:0]  axi_awid,
  input logic [17:0] axi_awaddr,
  input logic [7:0]  axi_awlen,
  input logic [2:0]  axi_awsize,
  input logic [1:0]  axi_awburst,
  input logic        axi_awvalid,
  input logic        axi_awready,
  input logic [31:0] axi_wdata,
  input logic [3:0]  axi_wstrb,
  input logic        axi_wlast,
  input logic        axi_wvalid,
  input logic        axi_wready,
  input logic [3:0]  axi_bid,
  input logic [1:0]  axi_bresp,
  input logic        axi_bvalid,
  input logic        axi_bready,
  input logic [3:0]  axi_arid,
  input logic [17:0] axi_araddr,
  input logic [7:0]  axi_arlen,
  input logic [2:0]  axi_arsize,
  input logic [1:0]  axi_arburst,
  input logic        axi_arvalid,
  input logic        axi_arready,
  input logic [3:0]  axi_rid,
  input logic [31:0] axi_rdata,
  input logic [1:0]  axi_rresp,
  input logic        axi_rlast,
  input logic        axi_rvalid,
  input logic        axi_rready
`else
  ,
  input logic        avm_read,
  input logic        avm_write,
  input logic [17:0] avm_address,
  input logic [31:0] avm_writedata,
  input logic        avm_waitrequest,
  input logic [1:0]  avm_response,
  input logic [8:0]  avm_burstcount
`endif
);
  sc_hub_assertions assertions_inst (
    .*
  );
endmodule
